name: appscom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  photo_view: ^0.15.0
  shared_preferences: ^2.3.3
  avatar_glow: ^3.0.1
# image_gallery_saver: ^2.0.3
  flutter_pdfview: ^1.3.4
  syncfusion_flutter_pdfviewer: ^27.2.3
  url_launcher: ^6.3.1
  sizer: ^3.0.5
  carousel_slider: ^5.0.0
  animate_do: ^3.3.4
  rive: ^0.13.17
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  table_calendar: ^3.0.6
  http: ^1.2.2
  go_router: ^14.2.0
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  device_preview: ^1.2.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.4
  change_app_package_name: ^1.4.0

flutter_icons:
  android:
    generate: true
    image_path: "assets/logo/logo.png"
    min_sdk_android: 21
  ios:
    generate: true
    image_path: "assets/logo/logo.png"
  web:
    generate: true
    image_path: "path/to/image.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

# For information on the generic Dart part of this file, see the
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/rive/
    # otras rutas de assets...
    - assets/pdf/

    # PNGs
    - assets/png/
    - assets/png/donativo/
    - assets/png/calendarios/
    - assets/png/fotografias/
    - assets/png/carreras/
    - assets/png/equipo/


    # SVGs
    - assets/svg/
    - assets/svg/login/
    - assets/svg/onboarding/

    # Colors


    # google fonts for testing
    - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abolition
      fonts:
        - asset: assets/fonts/Abolition-Regular.ttf

    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/Proxima-Nova.otf

    - family: Intel
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
